### Delete task by id [DELETE /v1/tasks/{id}]
Update task by id

+ Parameters
    + id: 12 (number) - The id of the task.

+ Response 204 (application/json)

+ Response 404 (application/json)
    + Attributes
        <!-- include(../../util/errorNotFound.apib) -->
